kind: pipeline
name: default
type: docker
trigger:
  event:
    - pull_request
    - push
  branch:
    - master
platform:
  os: linux
  arch: amd64
steps:
  - name: install-dependencies
    pull: if-not-exists
    image: lucianoajunior/api.raxadinha.dev:latest
    commands:
      - apk --update add --no-cache git
      - cd src
      - composer install --prefer-dist --no-suggest
      - mv .env.example .env
  - name: unit-tests
    pull: if-not-exists
    image: lucianoajunior/api.raxadinha.dev:latest
    commands:
      - cd src
      - ./vendor/bin/phpunit --no-coverage
  - name: coverage-tests
    pull: if-not-exists
    image: lucianoajunior/api.raxadinha.dev:latest
    environment:
      CODECOV_TOKEN: ec5fa15a-b131-41cb-94f5-e43b71c37618
    commands:
      - cd src
      - ./vendor/bin/phpunit --coverage-clover=coverage.xml
      - curl -s https://codecov.io/bash | bash -s --