version: '3'
services:
  app:
    container_name: api.raxadinha.dev
    build:
      context: .
      args:
        APP_ENV: local
    volumes:
      - ./src:/app

  web:
    container_name: nginx.raxadinha.dev
    image: nginx:1.17.9
    working_dir: /app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - "80:80"
      - "443:443"

  db.raxadinha.dev:
    container_name: db.raxadinha.dev
    build:
      context: ./docker/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped