---
apiVersion: v1
kind: Namespace
metadata:
  name: ms-raxadinha
  labels:
    name: ms-raxadinha
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ms-raxadinha
 labels:
   app: ms-raxadinha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-raxadinha
  template:
    metadata:
      labels:
        app: ms-raxadinha
    spec:
      containers:
      - name: raxadinha
        image: lucianoajunior/api.raxadinha.dev:latest
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 80
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
      restartPolicy: Always
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-raxadinha
  namespace: ms-raxadinha
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-raxadinha
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  namespace: ms-raxadinha
  labels:
    app: ms-raxadinha
  name: ms-raxadinha
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ms-raxadinha
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ms-raxadinha
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: api.raxadinha.k8s
    http:
      paths:
      - path: /
        backend:
          serviceName: ms-raxadinha
          servicePort: 80